name: "dispatch"

on:
  workflow_dispatch:
    inputs:
      octoprint_version:
        description: "OctoPrint version (leave empty to use latest stable release)"
        required: false
        default: ''

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest
    steps:

    - name: "⬇ Checkout"
      uses: actions/checkout@v2

    - id: my_latestrelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}

    - id: octoprint_latestrelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: OctoPrint/OctoPrint

    - id: octopi_latestrelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: guysoft/OctoPi

    - name: "print versions"
      run: |
        echo "my version: ${{ steps.my_latestrelease.outputs.release }}"
        echo "octoprint version: ${{ steps.octoprint_latestrelease.outputs.release }}"
        echo "my version: ${{ steps.octopi_latestrelease.outputs.release }}"
